/* --------------------------------------------------------------------------------
 #
 #	4DPlugin.h
 #	source generated by 4D Plugin Wizard
 #	Project : Get Folder Size
 #	author : miyako
 #	2017/11/02
 #
 # --------------------------------------------------------------------------------*/



// --- Get Folder Size
void Get_folder_size(sLONG_PTR *pResult, PackagePtr pParams);
