/* --------------------------------------------------------------------------------
 #
 #	4DPlugin-Get-Folder-Size.h
 #	source generated by 4D Plugin Wizard
 #	Project : Get Folder Size
 #	author : miyako
 #	2025/03/22
 #  
 # --------------------------------------------------------------------------------*/

#ifndef PLUGIN_GET_FOLDER_SIZE_H
#define PLUGIN_GET_FOLDER_SIZE_H

#include "4DPluginAPI.h"
#include "C_TEXT.h"
#include "C_REAL.h"

#pragma mark -

static void Get_folder_size(PA_PluginParameters params);

#endif /* PLUGIN_GET_FOLDER_SIZE_H */
